name: Release

on:
    push:
        branches:
            - main
        tags:
            - "v*"

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      artifact: uniclip-linux
                    - os: macos-latest
                      artifact: uniclip-macos
                    - os: windows-latest
                      artifact: uniclip-windows.exe

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Build binary
              run: cargo build --release

            - name: Rename executable for platform
              run: |
                  if [[ "$RUNNER_OS" == "Windows" ]]; then mv target/release/uniclip.exe uniclip-windows.exe; fi
                  if [[ "$RUNNER_OS" == "Linux" ]]; then mv target/release/uniclip uniclip-linux; fi
                  if [[ "$RUNNER_OS" == "macOS" ]]; then mv target/release/uniclip uniclip-macos; fi
              shell: bash

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.artifact }}
                  path: ${{ matrix.artifact }}

    release:
        name: Create GitHub Release
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts/

            - name: Display downloaded files
              run: ls -R artifacts/

            - name: Upload release assets
              uses: softprops/action-gh-release@v2
              with:
                  files: artifacts/**/*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
